### PR TITLE
add type defs

### PR DESCRIPTION
**Pull request by dbushong**
* chore: add package-lock
* chore: add type defs
* chore: update node versions for testing

---
_This PR was started by: [git wf pr](https://github.com/groupon/git-workflow/releases/tag/v1.0.3)_

### CODE REVIEW

**Review by hybrist — APPROVED** [review]
Thanks and sorry for the delay. Would you be interested in moving this to the groupon org and take ownership?

**Comment by hybrist** [comment]
(Alternatively I can also give you access to this repo of course.)

**Comment by hybrist** [comment]
Heh, looks like you already had write access. Also Chris Khoo and Adam Geitgey which dates the creation of the repo.

**Comment by ageitgey** [comment]
I gonna hack this repo so much with my l33t sk1llz - watch out!!

dumb

**Comment by hybrist** [comment]
Stop flying your spy drones to my workplace to monitor my browsing habits, Adam. It's starting to get awkward.

(I did remove Adam and Chris from the repo unless either of them feels passionate about contributing of course.)

**Comment by dbushong** [comment]
Sure.  Can you `npub` this one, and I'll add a ticket for us to do that one of these days?

**Comment by hybrist** [comment]
Published as 1.1.2. `npub` - that was a thing.

**Pull request merged**
